// Generated by apigen cli from backend/openapi.json — do not edit by hand.
// Every feature route as `api <area> <action>`; the call goes through callRoute
// (cli/src/lib/apigen-call.ts), which uses this CLI's own sign-in and client, and bad
// input through failRoute (the CLI's own error output). A file upload's body is a multipart
// FormData, its file fields read from the paths given, sent through callForm.
import { readFileSync } from 'node:fs';
import { basename } from 'node:path';
import { Command } from 'commander';
import { callForm, callRoute, failRoute } from '../lib/apigen-call.js';

type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json' | 'file';
interface Field { name: string; kind: Kind; required: boolean; choices?: string[] }
interface Route { name: string; method: string; path: string; summary: string; pathParams: string[]; query: Field[]; body: Field[] | null; form?: boolean }

export const API_ROUTES: Array<{ area: string; routes: Route[] }> = [
 {
  "area": "audit-log",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/audit-log",
    "summary": "List audit log",
    "pathParams": [],
    "query": [
     {
      "name": "action",
      "kind": "string",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "billing",
  "routes": [
   {
    "name": "cancel",
    "method": "POST",
    "path": "/api/v1/billing/cancel",
    "summary": "Cancel the active paid subscription at period end.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "checkout",
    "method": "POST",
    "path": "/api/v1/billing/checkout",
    "summary": "Create a Plugipay checkout session for the selected LinkSnap tier.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "currency",
      "kind": "string",
      "required": false
     },
     {
      "name": "plan",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "downgrade",
    "method": "POST",
    "path": "/api/v1/billing/downgrade",
    "summary": "/billing/webhook/storlaunch was the legacy receiver back when LinkSnap routed checkout through Storlaunch's Midtrans wrapper.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "plan",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "history",
    "method": "GET",
    "path": "/api/v1/billing/history",
    "summary": "Billing history (paginated)",
    "pathParams": [],
    "query": [
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "invoices",
    "method": "GET",
    "path": "/api/v1/billing/invoices",
    "summary": "Alias for history",
    "pathParams": [],
    "query": [
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "plan",
    "method": "GET",
    "path": "/api/v1/billing/plan",
    "summary": "Return current user's plan with all limits",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "plans",
    "method": "GET",
    "path": "/api/v1/billing/plans",
    "summary": "Return all 3 plans with IDR prices (public, no auth needed)",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "subscription",
    "method": "GET",
    "path": "/api/v1/billing/subscription",
    "summary": "Return current subscription details",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "usage",
    "method": "GET",
    "path": "/api/v1/billing/usage",
    "summary": "Return current usage vs plan limits",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "domains",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/domains",
    "summary": "Add custom domain",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "domain",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/domains/{id}",
    "summary": "Remove domain",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/domains/{id}",
    "summary": "Get single domain",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/domains",
    "summary": "List custom domains",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "verify",
    "method": "POST",
    "path": "/api/v1/domains/{id}/verify",
    "summary": "Verify domain DNS",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "links",
  "routes": [
   {
    "name": "bulk",
    "method": "POST",
    "path": "/api/v1/links/bulk",
    "summary": "Bulk operations",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "action",
      "kind": "string",
      "required": false
     },
     {
      "name": "ids",
      "kind": "string",
      "required": false
     },
     {
      "name": "tag",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/links",
    "summary": "Create link",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "expiresAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "maxClicks",
      "kind": "string",
      "required": false
     },
     {
      "name": "slug",
      "kind": "string",
      "required": false
     },
     {
      "name": "tags",
      "kind": "string",
      "required": false
     },
     {
      "name": "url",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/links/{id}",
    "summary": "Delete link",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "export",
    "method": "GET",
    "path": "/api/v1/links/export",
    "summary": "Export links - MUST be before /:id to avoid matching 'export' as an ID",
    "pathParams": [],
    "query": [
     {
      "name": "format",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/links/{id}",
    "summary": "Get link by ID or slug",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "import",
    "method": "POST",
    "path": "/api/v1/links/import",
    "summary": "Import links (JSON body)",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "dryRun",
      "kind": "string",
      "required": false
     },
     {
      "name": "links",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/links",
    "summary": "List links",
    "pathParams": [],
    "query": [
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     },
     {
      "name": "order",
      "kind": "string",
      "required": false
     },
     {
      "name": "q",
      "kind": "string",
      "required": false
     },
     {
      "name": "sort",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false
     },
     {
      "name": "tag",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "stats",
    "method": "GET",
    "path": "/api/v1/links/{id}/stats",
    "summary": "List stats",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "from",
      "kind": "string",
      "required": false
     },
     {
      "name": "to",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "stats-export",
    "method": "GET",
    "path": "/api/v1/links/{id}/stats/export",
    "summary": "Get link stats",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "format",
      "kind": "string",
      "required": false
     },
     {
      "name": "from",
      "kind": "string",
      "required": false
     },
     {
      "name": "to",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/links/{id}",
    "summary": "Update link",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "expiresAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "maxClicks",
      "kind": "string",
      "required": false
     },
     {
      "name": "slug",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false
     },
     {
      "name": "tags",
      "kind": "string",
      "required": false
     },
     {
      "name": "url",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "qr-codes",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/qr-codes",
    "summary": "Create QR code",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "expiresAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "linkId",
      "kind": "string",
      "required": false
     },
     {
      "name": "logoRunRef",
      "kind": "string",
      "required": false
     },
     {
      "name": "maxScans",
      "kind": "string",
      "required": false
     },
     {
      "name": "styleConfig",
      "kind": "string",
      "required": false
     },
     {
      "name": "tags",
      "kind": "string",
      "required": false
     },
     {
      "name": "title",
      "kind": "string",
      "required": false
     },
     {
      "name": "url",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/qr-codes/{id}",
    "summary": "Delete QR code",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "download",
    "method": "GET",
    "path": "/api/v1/qr-codes/{id}/download",
    "summary": "Download QR code image — MUST be before /:id Supports both Authorization header and ?token= query parameter",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "format",
      "kind": "string",
      "required": false
     },
     {
      "name": "token",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "download-token",
    "method": "POST",
    "path": "/api/v1/qr-codes/{id}/download-token",
    "summary": "Generate download token — MUST be before /:id",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/qr-codes/{id}",
    "summary": "Get single QR code",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/qr-codes",
    "summary": "List QR codes",
    "pathParams": [],
    "query": [
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     },
     {
      "name": "linkId",
      "kind": "string",
      "required": false
     },
     {
      "name": "q",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false
     },
     {
      "name": "tag",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "stats",
    "method": "GET",
    "path": "/api/v1/qr-codes/{id}/stats",
    "summary": "Get QR code stats — MUST be before /:id",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "from",
      "kind": "string",
      "required": false
     },
     {
      "name": "to",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/qr-codes/{id}",
    "summary": "Update QR code",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "expiresAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "logoRunRef",
      "kind": "string",
      "required": false
     },
     {
      "name": "maxScans",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false
     },
     {
      "name": "styleConfig",
      "kind": "string",
      "required": false
     },
     {
      "name": "tags",
      "kind": "string",
      "required": false
     },
     {
      "name": "title",
      "kind": "string",
      "required": false
     },
     {
      "name": "url",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "upload-logo",
    "method": "POST",
    "path": "/api/v1/qr-codes/upload-logo",
    "summary": "Upload a logo for the QR code's center (on plans with qrLogoEnabled — every plan today)",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "logo",
      "kind": "file",
      "required": true
     }
    ],
    "form": true
   }
  ]
 },
 {
  "area": "tags",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/tags",
    "summary": "Create tag",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/tags/{id}",
    "summary": "Detaches it from every link and QR code.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/tags",
    "summary": "List tags",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/tags/{id}",
    "summary": "Rename tag — the tag keeps its id, so every link and QR code that carries it follows the rename for free (implicit m2m join rows key on the id, not the name).",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "webhooks",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/webhooks",
    "summary": "Create endpoint — returns the whsec_ secret once.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "events",
      "kind": "string",
      "required": false
     },
     {
      "name": "url",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/webhooks/{id}",
    "summary": "Remove endpoint.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "deliveries",
    "method": "GET",
    "path": "/api/v1/webhooks/deliveries",
    "summary": "List webhook deliveries.",
    "pathParams": [],
    "query": [
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false
     },
     {
      "name": "subscriptionId",
      "kind": "string",
      "required": false
     },
     {
      "name": "type",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "deliveries-retry",
    "method": "POST",
    "path": "/api/v1/webhooks/deliveries/{id}/retry",
    "summary": "Retry a webhook delivery.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "event-types",
    "method": "GET",
    "path": "/api/v1/webhooks/event-types",
    "summary": "The event catalogue: every type LinkSnap sends, with what fires it — the dashboard's event picker renders from this.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "get-deliveries",
    "method": "GET",
    "path": "/api/v1/webhooks/deliveries/{id}",
    "summary": "Get a webhook delivery, with every attempt made at it.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/webhooks",
    "summary": "List endpoints (never includes the secret).",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/webhooks/{id}",
    "summary": "Pause / resume delivery, or edit the endpoint's url / events.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "active",
      "kind": "string",
      "required": false
     },
     {
      "name": "events",
      "kind": "string",
      "required": false
     },
     {
      "name": "url",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "workspaces",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/workspaces",
    "summary": "Create new workspace",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "create-current-members",
    "method": "POST",
    "path": "/api/v1/workspaces/current/members",
    "summary": "Invite member",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "email",
      "kind": "string",
      "required": false
     },
     {
      "name": "role",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "current",
    "method": "GET",
    "path": "/api/v1/workspaces/current",
    "summary": "Get active workspace details",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "current-members",
    "method": "GET",
    "path": "/api/v1/workspaces/current/members",
    "summary": "List members",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "current-stats",
    "method": "GET",
    "path": "/api/v1/workspaces/current/stats",
    "summary": "Workspace stats",
    "pathParams": [],
    "query": [
     {
      "name": "from",
      "kind": "string",
      "required": false
     },
     {
      "name": "to",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "delete-current-members",
    "method": "DELETE",
    "path": "/api/v1/workspaces/current/members/{id}",
    "summary": "Remove member",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/workspaces",
    "summary": "Huudis is the source of truth.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "switch",
    "method": "POST",
    "path": "/api/v1/workspaces/switch",
    "summary": "Switch active workspace",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "workspaceId",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "update-current",
    "method": "PATCH",
    "path": "/api/v1/workspaces/current",
    "summary": "Update active workspace",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "update-current-members",
    "method": "PATCH",
    "path": "/api/v1/workspaces/current/members/{id}",
    "summary": "Change a member's role.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "role",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 }
];

// A field whose flag would clash with this command's own options or the CLI's global ones
// is given as --field-<name>.
const RESERVED = new Set(['help', 'version', 'json', 'profile', 'api', 'on-behalf-of', 'color', 'no-color', 'body-json']);
const plain = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
const flag = (name: string): string => (RESERVED.has(plain(name)) ? `field-${plain(name)}` : plain(name));
const camel = (name: string): string => flag(name).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function value(field: Field, raw: string): unknown {
  if (field.kind === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(`--${flag(field.name)} must be a number`);
    return n;
  }
  if (field.kind === 'boolean') return raw === '' || raw === 'true' || raw === '1' || raw === 'yes';
  if (field.kind === 'array') return raw.trim().startsWith('[') ? JSON.parse(raw) : raw.split(',').map((x) => x.trim()).filter(Boolean);
  if (field.kind === 'json') return JSON.parse(raw);
  if (field.choices && !field.choices.includes(raw)) throw new Error(`--${flag(field.name)} must be one of: ${field.choices.join(', ')}`);
  return raw;
}

export function buildApiCommand(): Command {
  const api = new Command('api').description('Every route of the API, one command each (generated from the API spec)');
  for (const { area, routes } of API_ROUTES) {
    const group = new Command(area).description(`${area} routes`);
    for (const route of routes) {
      const cmd = new Command(route.name).description(`${route.summary} (${route.method} ${route.path})`);
      for (const p of route.pathParams) cmd.argument(`<${p}>`);
      const fields = [...route.query, ...(route.body ?? [])];
      for (const f of fields) {
        const hint = f.kind === 'file' ? ' (path of the file to upload)' : f.choices ? ` (${f.choices.join('|')})` : f.kind === 'json' || f.kind === 'array' ? ` (${f.kind})` : '';
        cmd.option(f.kind === 'boolean' ? `--${flag(f.name)} [value]` : `--${flag(f.name)} <${f.kind === 'file' ? 'path' : 'value'}>`, `${f.required ? 'required' : 'optional'}${hint}`);
      }
      if (route.body && !route.form) cmd.option('--body-json <json>', 'the whole body as JSON (fields given as flags override it)');
      cmd.action(async (...parts: unknown[]) => {
        const command = parts[parts.length - 1] as Command;
        const opts = command.opts() as Record<string, string | boolean | undefined>;
        try {
        let path = route.path;
        route.pathParams.forEach((p, i) => { path = path.replace(`{${p}}`, encodeURIComponent(String(parts[i]))); });
        const query: Record<string, unknown> = {};
        for (const f of route.query) {
          const raw = opts[camel(f.name)];
          if (raw !== undefined) query[f.name] = value(f, raw === true ? '' : String(raw));
        }
        if (route.form) {
          const form = new FormData();
          const missing: string[] = [];
          for (const f of route.body ?? []) {
            const raw = opts[camel(f.name)];
            if (raw === undefined) {
              if (f.required) missing.push(`--${flag(f.name)}`);
              continue;
            }
            if (f.kind === 'file') form.append(f.name, new Blob([new Uint8Array(readFileSync(String(raw)))]), basename(String(raw)));
            else {
              const v = value(f, raw === true ? '' : String(raw));
              form.append(f.name, typeof v === 'string' ? v : JSON.stringify(v));
            }
          }
          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);
          await callForm(command, route.method, path, query, form);
          return;
        }
        let body: Record<string, unknown> | undefined;
        if (route.body) {
          body = opts.bodyJson ? (JSON.parse(String(opts.bodyJson)) as Record<string, unknown>) : {};
          for (const f of route.body) {
            const raw = opts[camel(f.name)];
            if (raw !== undefined) body[f.name] = value(f, raw === true ? '' : String(raw));
          }
          const missing = route.body.filter((f) => f.required && body![f.name] === undefined).map((f) => `--${flag(f.name)}`);
          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);
        }
        await callRoute(command, route.method, path, query, body);
        } catch (err) {
          await failRoute(command, err);
        }
      });
      group.addCommand(cmd);
    }
    api.addCommand(group);
  }
  return api;
}
